var data =
  [{
    name:"Spotnride",
    content: "Spotnride était notre premier projet pédagogique, et cela fût très enrichissant blablabla",
    date:"20/11/17",
    tools:"html5/css3",
    link:'none',
    pictures:['image1','image2','image3'],
    color:"#ff1ac6",
    colorBg:"#ff99e6"
  },
  {
    name:"Nespresso",
    content:0,
    date:"27/11/17",
    tools:"Photoshop",
    link:"https://ibb.co/hCUtAx",
    content:"blablablablablablablablablalblalblalblzlblzlblzll",
    pictures:['image1','image2','image3'],
    color:"#ffcc80",
    colorBg:"#ff9900",
    bgImage:0
  },
  {
    name:"Rewind",
    content:0,
    date:"18/12/17",
    tools:0,
    link:0,
    content:0,
    pictures:0,
    color:"#2d8659",
    colorBg:"#66cc99"
  },
  {
    name:"Amazon",
    content:0,
    date:"30/01/17",
    tools:0,
    link:0,
    content:0,
    pictures:0,
    color:"#ffe066",
    colorBg:"#e6b800"
  },
  {
    name:"Erreur 404",
    content:0,
    date:"??/??/??",
    tools:0,
    link:0,
    content:0,
    pictures:0,
    color:"#cc0000",
    colorBg:"#ff3333"
  }];
